apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-servicemonitor
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  endpoints:
    - port: postgres
      interval: 30s
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mongo-servicemonitor
  labels:
    app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  endpoints:
    - port: mongo
      interval: 30s
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-servicemonitor
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  endpoints:
    - port: redis
      interval: 30s
      path: /metrics
