apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: R2ZQbStlRWhsUnZvVGFDZCtUbnFhQ0g4TWE2cW5UZTBvS0Y4VEs3MVNmdz0K
  MONGO_ROOT_PASSWORD: NkZGNE95dkpDSFg4UkRvT2dMdTJQbkttNG93MHBsSmh5YUdIdHdWU21oUT0K
