apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  labels:
    app: analytics-service
    tier: application
type: Opaque
data:
  JWT_SECRET: anJmQXpDandFWDA4Vlo1MTZUM0hnWjJ1d3FaVDBoRUtQUDFZdC9VaERkYz0K
  JWT_REFRESH_SECRET: SDI4Zm5Oc0IvcjRvd2FhSjRwSTVQVVdOUHZIc0RvS1pCZWFyZDRacmN1RT0K
